### ISSUE TITLE
Dependency mismatch between nuspec and project

### ISSUE THREAD

**Issue by Kesmy** [alexandrnikitin/Topshelf.Unity#15]
The project file contains explicit dependencies on Topshelf 4.2.0 and Unity.Abstractions 5.11.1, but the nuspec allows for lower versions.

One or the other should be changed.

Unless there are objections, or someone else gets to it first, I'll submit a PR to update the nuspec to 4.2.0 & 5.11.1 today when I have the opportunity.

**Comment by alexandrnikitin** [comment]
@Kesmy Thank you for reporting this. Why is it an issue? Dependencies in nuspec specified in ranges e.g. `[4.0.0, 6.0.0)` because those versions are compatible with the project. I don't see a point to specify exact dependency in nuspec. While in proj file you have to put exact version, because it's implementation.

**Comment by Kesmy** [comment]
@alexandrnikitin It causes a compiler error CS1705 re the mismatch between the explicit version and nuspec-specified version when using project packagereferences, which automatically use the lowest-specified version from the nuspec:

CS1705 Assembly 'Topshelf.Unity' with identity...uses 'Topshelf, Version=4.2.0.194...' which has a higher version than referenced assembly 'Topshelf' with identity 'Topshelf, Version=4.0.0.0...'

**Comment by alexandrnikitin** [comment]
Closed by #18

**Comment by alexandrnikitin** [comment]
Published 4.0.1
